# Generated by Django 5.1.4 on 2025-01-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_articlecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="article.articlecomment",
            ),
            preserve_default=False,
        ),
    ]
