# Generated by Django 5.1.4 on 2025-01-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_article_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlecomment",
            name="content",
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="comment",
            field=models.CharField(default=5, max_length=100, verbose_name="comment"),
            preserve_default=False,
        ),
    ]
