# Generated by Django 5.1.4 on 2025-01-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_remove_articlecomment_content_articlecomment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlecomment",
            old_name="comment",
            new_name="content",
        ),
    ]
