# Generated by Django 5.1.4 on 2025-01-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_rename_comment_articlecomment_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="comment",
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
